# Run: ./ops/experiment.py local configs/bo/eggroll/smoke/cartpole_v1_turbo_enn_smoke.toml

[experiment]
exp_dir = "/tmp/yubo_eggroll_turbo_enn_smoke"
env_tag = "gymnax:CartPole-v1"
policy_tag = "eggroll-ac-mlp-8x1-pqn"
# num_arms = 1
# # num_rounds = 2

num_arms = 1
total_timesteps = 500000000
num_reps = 10
runtime_device = "cuda"
local_workers = 1
b_trace = true

[optimizer]
name = "turbo-enn-fit-ucb"

[optimizer.params]
steps_per_episode = 10
num_envs = 1
deterministic_policy = false
param_scale = 0.1
