from functools import partial

from . import designer_registry_builders as _b

_SIMPLE_BUILDERS = {
    "cma": partial(_b._build_policy_ctor, module="optimizer.cma_designer", name="CMAESDesigner"),
    "dngo": partial(_b._build_policy_ctor, module="optimizer.dngo_designer", name="DNGODesigner"),
    "optuna": partial(_b._build_policy_ctor, module="optimizer.optuna_designer", name="OptunaDesigner"),
    "ax": partial(_b._build_policy_ctor, module="optimizer.ax_designer", name="AxDesigner"),
    "random": partial(_b._build_policy_ctor, module="optimizer.random_designer", name="RandomDesigner"),
    "ppo": _b._build_ppo,
    "ppo-ac": _b._build_ppo,
    "ppo-pg": _b._build_ppo_pg,
    "smac": partial(_b._build_policy_ctor, module="optimizer.smac_designer", name="SMACDesigner"),
    "sobol": partial(_b._build_policy_ctor, module="optimizer.sobol_designer", name="SobolDesigner"),
    "lhd": partial(_b._build_policy_ctor, module="optimizer.lhd_designer", name="LHDDesigner"),
    "center": partial(_b._build_policy_ctor, module="optimizer.center_designer", name="CenterDesigner"),
    "vecchia": lambda ctx: _b._load_symbol("optimizer.vecchia_designer", "VecchiaDesigner")(ctx.policy, num_candidates_per_arm=ctx.default_num_X_samples),
    "mcmcbo": lambda ctx: _b._load_symbol("optimizer.mcmc_bo_designer", "MCMCBODesigner")(ctx.policy, num_init=ctx.init_yubo_default),
    "maximin": partial(_b._build_maximin, toroidal=False),
    "maximin-toroidal": partial(_b._build_maximin, toroidal=True),
    "variance": partial(_b._build_bt_acq, module="acq.acq_var", name="AcqVar"),
    "btsobol": partial(_b._build_bt_acq, module="acq.acq_sobol", name="AcqSobol"),
    "ts": partial(
        _b._build_bt_acq,
        module="acq.acq_ts",
        name="AcqTS",
        acq_kwargs={"sampler": "cholesky", "num_candidates": 1000},
    ),
    "ts-10000": partial(
        _b._build_bt_acq,
        module="acq.acq_ts",
        name="AcqTS",
        acq_kwargs={"sampler": "lanczos", "num_candidates": 10000},
    ),
    "sr": partial(_b._build_bt_acq, module="botorch.acquisition.monte_carlo", name="qSimpleRegret"),
    "ucb": partial(
        _b._build_bt_acq,
        module="botorch.acquisition.monte_carlo",
        name="qUpperConfidenceBound",
        acq_kwargs={"beta": 1},
    ),
    "ei": partial(
        _b._build_bt_acq,
        module="botorch.acquisition.monte_carlo",
        name="qNoisyExpectedImprovement",
        acq_kwargs={"X_baseline": None},
    ),
    "lei": partial(
        _b._build_bt_acq,
        module="botorch.acquisition.logei",
        name="qLogNoisyExpectedImprovement",
        acq_kwargs={"X_baseline": None},
    ),
    "lei-m": partial(
        _b._build_bt_acq,
        module="botorch.acquisition.logei",
        name="qLogNoisyExpectedImprovement",
        acq_kwargs={"X_baseline": None},
        start_at_max=True,
    ),
    "gibbon": partial(
        _b._build_bt_acq,
        module="botorch.acquisition.max_value_entropy_search",
        name="qLowerBoundMaxValueEntropy",
        acq_kwargs={"candidate_set": None},
        opt_sequential=True,
    ),
    "dpp": lambda ctx: _b._build_bt_acq(
        ctx,
        module="acq.acq_dpp",
        name="AcqDPP",
        init_sobol=1,
        acq_kwargs={"num_X_samples": ctx.default_num_X_samples},
    ),
    "turbo-1": partial(_b._build_turbo_ref, kind="turbo-1"),
    "turbo-1-iso": partial(_b._build_turbo_ref, kind="turbo-1-iso"),
    "turbo-0": partial(_b._build_turbo_ref, kind="turbo-0"),
    "turbo-enn-p-hnsw": partial(_b._build_turbo_enn, kind="turbo-enn-p-hnsw"),
    "turbo_py-enn-p": partial(_b._build_turbo_enn_py, kind="turbo_py-enn-p"),
    "turbo_py-enn-fit-ucb": partial(_b._build_turbo_enn_py, kind="turbo_py-enn-fit-ucb"),
    "turbo-zero": partial(_b._build_turbo_enn, kind="turbo-zero"),
    "turbo-one": partial(_b._build_turbo_enn, kind="turbo-one"),
    "turbo-one-nds": partial(_b._build_turbo_enn, kind="turbo-one-nds"),
    "turbo-one-ucb": partial(_b._build_turbo_enn, kind="turbo-one-ucb"),
    "lhd_only": partial(_b._build_turbo_enn, kind="lhd_only"),
    "morbo-zero": partial(_b._build_turbo_enn, kind="morbo-zero"),
    "morbo-one": partial(_b._build_turbo_enn, kind="morbo-one"),
    "morbo-enn": partial(_b._build_turbo_enn, kind="morbo-enn"),
    "mts": partial(_b._build_mts, kind="mts"),
    "mts-stagger": partial(_b._build_mts, kind="mts-stagger"),
    "mts-ts": partial(_b._build_mts, kind="mts-ts"),
    "mts-meas": partial(_b._build_mts, kind="mts-meas"),
    "mtv": partial(_b._build_mtv_family, kind="mtv"),
    "pss": partial(_b._build_mtv_family, kind="pss"),
    "mtv-sts": partial(_b._build_mtv_family, kind="mtv-sts"),
    "mtv-mts": partial(_b._build_mtv_family, kind="mtv-mts"),
    "mtv-sts2": partial(_b._build_mtv_family, kind="mtv-sts2"),
    "mtv-sts-t": partial(_b._build_mtv_family, kind="mtv-sts-t"),
    "sts": partial(_b._build_mtv_family, kind="sts"),
    "sts-ch": partial(_b._build_mtv_family, kind="sts-ch"),
    "sts-ns": partial(_b._build_mtv_family, kind="sts-ns"),
    "sts-ui": partial(_b._build_mtv_family, kind="sts-ui"),
    "sts-t": partial(_b._build_mtv_family, kind="sts-t"),
    "sts-m": partial(_b._build_mtv_family, kind="sts-m"),
    "sts2": partial(_b._build_mtv_family, kind="sts2"),
    "path": partial(_b._build_pathwise, kind="path"),
    "path-b": partial(_b._build_pathwise, kind="path-b"),
    "path-m": partial(_b._build_pathwise, kind="path-m"),
    "sobol_ucb": partial(_b._build_sobol_mc, kind="sobol_ucb"),
    "sobol_ei": partial(_b._build_sobol_mc, kind="sobol_ei"),
    "sobol_gibbon": partial(_b._build_sobol_mc, kind="sobol_gibbon"),
}


_SIMPLE_DISPATCH = _SIMPLE_BUILDERS
