import math

import torch

from .sparse_jl_t_hash import (
    CHUNK_SIZE,
    compute_rows_and_signs,
    compute_rows_and_signs_wr,
)


def _accumulate_into_rows(
    y: torch.Tensor,
    flat_values: torch.Tensor,
    offset: int,
    d: int,
    s: int,
    seed: int,
    rows_signs_fn,
) -> None:
    n = flat_values.numel()
    if n == 0:
        return
    device = y.device
    dtype = y.dtype
    inv_sqrt_s = 1.0 / math.sqrt(s)

    for start in range(0, n, CHUNK_SIZE):
        end = min(start + CHUNK_SIZE, n)
        sub = flat_values[start:end]
        global_idx = torch.arange(offset + start, offset + end, dtype=torch.int64, device=device)
        rows, signs = rows_signs_fn(global_idx, d, s, seed, device)
        contrib = signs * sub.to(dtype).unsqueeze(1) * inv_sqrt_s
        y.scatter_add_(0, rows.reshape(-1), contrib.reshape(-1).to(dtype))


def accumulate_into(
    y: torch.Tensor,
    flat_values: torch.Tensor,
    offset: int,
    d: int,
    s: int,
    seed: int,
) -> None:
    """Accumulate JL contributions from flat_values into y (in-place)."""
    _accumulate_into_rows(y, flat_values, offset, d, s, seed, compute_rows_and_signs)


def accumulate_into_wr(
    y: torch.Tensor,
    flat_values: torch.Tensor,
    offset: int,
    d: int,
    s: int,
    seed: int,
) -> None:
    """Accumulate JL contributions using with-replacement row hashing."""
    _accumulate_into_rows(y, flat_values, offset, d, s, seed, compute_rows_and_signs_wr)


def accumulate_noise_into(
    y: torch.Tensor,
    num_dim_ambient: int,
    *,
    d: int,
    s: int,
    seed_jl: int,
    seed_noise: int,
    sigma: float,
    prob: float | None,
    chunk_size: int,
) -> None:
    """Accumulate JL contributions for a noise vector generated by seed_noise."""
    if num_dim_ambient <= 0:
        return
    if chunk_size <= 0:
        raise ValueError("chunk_size must be > 0")
    device = y.device
    dtype = y.dtype
    inv_sqrt_s = 1.0 / math.sqrt(s)

    g = torch.Generator(device=str(device))
    g.manual_seed(int(seed_noise))

    for start in range(0, int(num_dim_ambient), int(chunk_size)):
        end = min(start + int(chunk_size), int(num_dim_ambient))
        n = int(end - start)
        if prob is None:
            noise = torch.randn((n,), device=device, dtype=dtype, generator=g).mul_(float(sigma))
        else:
            u = torch.rand((n,), device=device, generator=g)
            mask = u < float(prob)
            noise = torch.randn((n,), device=device, dtype=dtype, generator=g).mul_(float(sigma))
            noise.mul_(mask)

        global_idx = torch.arange(start, end, dtype=torch.int64, device=device)
        rows, signs = compute_rows_and_signs(global_idx, d, s, seed_jl, device)
        contrib = signs * noise.unsqueeze(1) * inv_sqrt_s
        y.scatter_add_(0, rows.reshape(-1), contrib.reshape(-1).to(dtype))
