# macOS GPU environment (Apple MPS path, not CUDA).
channels:
  - pkgs/main
  - conda-forge
dependencies:
  - python=3.11.14
  - pip=26.0.1
  - faiss-cpu=1.9.0
  - nomkl=1.0
  - llvm-openmp=20.1.2
  - pytorch=2.5.1=gpu_mps_py311*
  - torchvision=0.20.1=mps_py311*
  - git-lfs=3.7.1
  - pip:
      - torchrl==0.11.0
      - tensordict==0.11.0
