# Run: ./ops/hyperscalees_llm.py local configs/pretrain/hyperscalees/paper/gsm8k_7w3b_eggroll.toml

[experiment]
exp_dir = "runs/yubo_hyperscalees/paper/gsm8k_7w3b_eggroll"
repo_dir = ".external/HyperscaleES"
log_file = "hyperscalees.log"
dry_run = false

[hyperscalees]
script = "general_do_evolution"

[args]
seed = 0
model_choice = "7w3B"
task = "gsm8k"
noiser = "eggroll"
num_epochs = 100
parallel_generations_per_gpu = 1024
generations_per_prompt = 8
thinking_length = 256
answer_length = 256
validate_every = 10
parallel_validations = 128
validation_iterations = 10
log_output_every = 10
output_directory = "runs/yubo_hyperscalees/paper/gsm8k_7w3b_eggroll/outputs"
wandb_directory = "runs/yubo_hyperscalees/paper/gsm8k_7w3b_eggroll"
wandb_mode = "offline"
wandb_name = "gsm8k_7w3b_eggroll"
track = false

[env.vars]
XLA_PYTHON_CLIENT_PREALLOCATE = "false"
