channels:
  - conda-forge
  - pkgs/main
dependencies:
  - python=3.11.14
  - pip=26.0.1
  - faiss-cpu=1.9.0
  - nomkl=1.0
  - llvm-openmp=20.1.2
  - pytorch=2.5.1
  - torchvision=0.20.1
  - git-lfs=3.7.1
  - pip:
      - torchrl==0.11.0
      - tensordict==0.11.0
