[rl]
algo = "mjx_ppo"

[rl.mjx_ppo]
exp_dir = "runs/rl/mjx/ppo_mjx_halfcheetah_test"
env_tag = "gymnasium:HalfCheetah-v5"
seed = 0
hidden_size = 256
log_interval = 10

[rl.mjx_ppo.collector]
total_frames = 1000000
num_envs = 2048
num_steps = 16

[rl.mjx_ppo.optim]
lr = 3e-4
minibatch_size = 8192
num_epochs = 4

[rl.run]
num_reps = 1
workers = 1
